# Folosim versiunea 3.8 pentru a suporta dependenta service_healthy
version: '3.8'

services:
  app:
    build: .
    container_name: tasma-app
    ports:
      - "8000:8000"
    networks:
      - tasma-network
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_healthy
    environment:
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "minio_user"
      MINIO_SECRET_KEY: "minio_password"

  db:
    image: postgres:14
    container_name: django-postgres
    environment:
      - POSTGRES_USER=django-user
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=django-db
    ports:
      - "5433:5432"
    networks:
      - tasma-network

  pghero:
    image: ankane/pghero
    container_name: pghero
    environment:
      - DATABASE_URL=postgres://django-user:passw0rd@db:5432/django-db
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
    networks:
      - tasma-network

  redis:
    image: redis:latest
    container_name: redis-primary
    ports:
      - "6379:6379"

    networks:
      - tasma-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - tasma-network

networks:
  tasma-network:
    external: false

volumes:
  minio_data:

