services:
  db:
    image: postgres:14
    container_name: django-postgres
    environment:
      - POSTGRES_USER=django-user
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=django-db
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
    container_name: redis-primary
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
      MINIO_NOTIFY_WEBHOOK_ENABLE_1: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_1: "http://host.docker.internal:8000/api/tasks/upload-webhook/"
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit_password
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3