name: Django CI/CD

on:
  push:
    branches:
      - main
      - mil/five

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.test.yaml"
          test-container: "app"
          test-command: "poetry run python manage.py test apps.tests"

      - name: Stop Containers
        if: always()
        run: docker compose -f docker-compose.test.yml down -v
