name: Django CI/CD

on:
  push:
    branches:
      - main
      - mil/five

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install uv
        run: |
          pip install uv
          uv lock
          uv sync --frozen

      - name: Run Ruff Lint
        run: uv run ruff check .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.test.yaml"
          test-container: "app"
          test-command: "uv run python manage.py test apps.tasks.tests"

      - name: Stop Containers
        if: always()
        run: docker compose -f ./docker-compose.test.yaml down -v
