name: Django CI/CD

on:
  push:
    branches:
      - main
      - mil/five

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

        # 2. Set up Python (pentru Ruff)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

          # 3. Install Poetry (pentru Ruff)
      - name: Install Poetry
        run: |
          pip install poetry
          poetry install --no-root
          
          # 4. Run Ruff linting (fără containere)
      - name: Run Ruff Lint
        run: poetry run ruff check .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Ruff Lint in App Container
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.test.yaml"
          test-container: "app"
          test-command: "poetry run ruff check ."

      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.test.yaml"
          test-container: "app"
          test-command: "./ci.sh" #"poetry run ruff check . &&poetry run python manage.py test apps.tasks.tests"

      - name: Stop Containers
        if: always()
        run: docker compose -f ./docker-compose.test.yml down -v
