name: Django CI/CD

on:
  push:
    branches:
      - main
      - mil/five

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: django-db
          POSTGRES_USER: django-user
          POSTGRES_PASSWORD: passw0rd
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U django-user -d django-db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      minio:
        image: minio/minio
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl --silent --fail http://localhost:9000/minio/health/live"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        command: server /data # Adaugă această linie

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13
      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install --no-root
          poetry lock

      - name: Wait for services
        run: |
          sleep 10 # Așteaptă 10 secunde pentru a permite serviciilor să pornească

      - name: Run makemigrations
        run: |
          poetry run python manage.py makemigrations
      - name: Run migrate
        run: |
          poetry run python manage.py migrate --noinput
      - name: Run Tests
        run: |
          poetry run python manage.py test