name: Django CI

on:
  push:
    branches:
      - master
      - mil/five

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Run Ruff linter
        run: poetry run ruff check .

      - name: Run tests
        run: poetry run python manage.py test