name: Django CI/CD

on:
  push:
    branches:
      - main
      - mil/five

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: django-db
          POSTGRES_USER: django-user
          POSTGRES_PASSWORD: passw0rd
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U django-user -d django-db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      minio:
        image: minio/minio
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        options: >-
          --health-cmd="curl --silent --fail http://localhost:9000/minio/health/live"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 9000:9000
    env:
      SECRET_KEY: django-insecure-padp=i%lys6-s3-+%vwbja9rxsu$=7undv(8txc$b^j90h)=ta
      DEBUG: "True"
      TESTING: "True"
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: localhost
      DB_PORT: 5432
      POSTGRES_DB: django-db
      POSTGRES_USER: django-user
      POSTGRES_PASSWORD: passw0rd

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13
      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install --no-root
          poetry lock
      - name: Wait for services to be ready
        run: |
          echo "Waiting for PostgreSQL and MinIO to be ready..."
          sleep 10
      - name: Run makemigrations
        run: |
          poetry run python manage.py makemigrations
      - name: Run migrate
        run: |
          poetry run python manage.py migrate --noinput
      - name: Run Tests
        run: |
          poetry run python manage.py test