#name: Django CI
#
#on:
#  push:
#    branches:
#      - master
#      - mil/five
#
#jobs:
#  build_and_test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.11'
#          cache: 'poetry'
#
#      - name: Install dependencies with Poetry
#        run: poetry install
#
#      - name: Run Ruff linter
#        run: poetry run ruff check .
#
#      - name: Run tests
#        run: poetry run python manage.py test


name: Django CI/CD

on:
  push:
    branches:
      - main
      - mil/five

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install --no-root
#          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test